version: '2'
services:
  is_rdbms:
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  identity-server:
    build:
      context: ../
      dockerfile: pattern-1/identity-server/Dockerfile
    environment:
      - SLEEP=10
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8000:8000"
      - "10500:10500"
      
